# Generated by Django 5.2.5 on 2026-01-30 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='نام پروژه')),
                ('project_address', models.TextField(verbose_name='آدرس')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_name', models.CharField(max_length=255, verbose_name='نام پنل')),
                ('board_id', models.SmallIntegerField(blank=True, default=1, verbose_name='شناسه ی برد')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel', to='project.project')),
            ],
            options={
                'verbose_name': 'پنل',
                'verbose_name_plural': 'پنل ها',
            },
        ),
    ]
