# Generated by Django 6.0.1 on 2026-05-10 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country_division', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_name', models.CharField(max_length=255, verbose_name='نام پنل')),
                ('board_id', models.SmallIntegerField(default=-1, null=True, verbose_name='شناسه ی برد')),
                ('volatge', models.IntegerField(null=True, verbose_name='ولتاژ')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'پنل',
                'verbose_name_plural': 'پنل ها',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='نام پروژه')),
                ('project_address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='طول جغرافیایی')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='عرض جغرافیایی')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='country_division.city', verbose_name='شهرستان')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='country_division.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
    ]
