# Generated by Django 6.0.1 on 2026-05-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panel',
            old_name='Project',
            new_name='project',
        ),
    ]
