# Generated by Django 6.0.1 on 2026-02-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_city_project_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='volatge',
            field=models.IntegerField(blank=True, null=True, verbose_name='ولتاژ'),
        ),
    ]
