# Generated by Django 6.0.1 on 2026-02-07 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_panel_volatge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_project', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='panel',
            name='board_id',
            field=models.SmallIntegerField(default=-1, null=True, verbose_name='شناسه ی برد'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='volatge',
            field=models.IntegerField(null=True, verbose_name='ولتاژ'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
    ]
