# Generated by Django 6.0.1 on 2026-05-15 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_project_panel_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='BoardReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='project.board')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strings', to='project.board')),
            ],
            options={
                'unique_together': {('board', 'string_id')},
            },
        ),
        migrations.CreateModel(
            name='StringReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.IntegerField()),
                ('current', models.IntegerField()),
                ('power', models.FloatField()),
                ('energy', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_readings', to='project.boardreading')),
                ('string', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='project.string')),
            ],
            options={
                'unique_together': {('board_reading', 'string')},
            },
        ),
        migrations.DeleteModel(
            name='Panel',
        ),
    ]
