# Generated by Django 6.0.1 on 2026-02-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عرض جغرافیایی'),
        ),
    ]
