# Generated by Django 6.0.1 on 2026-02-14 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_division', '0001_initial'),
        ('project', '0006_project_latitude_project_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='country_division.city', verbose_name='شهرستان'),
        ),
    ]
