# Generated by Django 6.0.1 on 2026-02-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_project_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panel',
            old_name='Project',
            new_name='project',
        ),
    ]
