# Generated by Django 6.0.1 on 2026-02-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_rename_project_panel_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='volatge',
        ),
        migrations.AddField(
            model_name='panel',
            name='kw',
            field=models.IntegerField(null=True, verbose_name='توان'),
        ),
    ]
