# Generated by Django 6.0.1 on 2026-05-15 15:07

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_remove_user_create_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=11, unique=True, validators=[utils.validators.mobile_validator]),
        ),
    ]
