# Generated by Django 6.0.1 on 2026-02-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_city_remove_user_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'ادمین'), (2, 'کاربرعادی')], default='2', max_length=1, verbose_name='نقش کاربر'),
        ),
    ]
